### ISSUE TITLE
Make on.exit explicit?

### ISSUE THREAD

**Issue by lionel-** [r-lib/ellipsis#15]
Should the UI be `on.exit(check_dots_unused())`? I think hiding the `on.exit()` makes it harder to read. Also harder to experiment with. Might also lead to bugs by writing things like:

```r
check_dots_unused()

on.exit(cleanup())
```

**Comment by hadley** [comment]
I think we should probably spell that out a bit more in the documentation, but it was a deliberate choice to make the API as simpler as possible.

**Comment by lionel-** [comment]
Would it make sense to use the prefix `scoped_`?

**Comment by hadley** [comment]
I think it's sort of an implementation detail that `on.exit()` is used, so I'd rather not expose it to the user.
