### ISSUE TITLE
check_dots_empty()?

### ISSUE THREAD

**Issue by lionel-** [r-lib/ellipsis#16]
Since `check_dots_used()` checks that dots were used, I would expect `check_dots_unused()` to check the opposite, that dots were passed but not used. `check_dots_empty()` seems like a better name.

**Comment by hadley** [comment]
Agreed

**Comment by lionel-** [comment]
It might also make sense to take `...` and check with `nargs()` in these functions. We don't need laziness to check empty dots and this should be faster.

**Comment by hadley** [comment]
Fixed by #20
