### ISSUE TITLE
CRAN errors on recent R-devel

### ISSUE THREAD

**Issue by echasnovski** [r-lib/ellipsis#33]
This is intended as a heads-up before many upcoming errors in CRAN checks.

Starting from R-devel version "2020-05-09 r78394", CRAN checks produce errors with the same message "'where' must be an environment" (for example, see [this log](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/ruler-00check.html)). This comes from `base::bquote(...)`, which is used in `ellipsis:::exit_handler(action)`.

Current _CRAN version_ of 'ellipsis' has implementation of [`exit_handler()`](https://github.com/r-lib/ellipsis/blob/77387d25aa670a8425df869b9bbbd1a3131d0410/R/check.R#L47-L51) using `bquote()` with `where` argument being a list. Recent update in R-devel explicitly prohibited `where` to be anything other than environment (see [this commit](https://github.com/wch/r-source/commit/0250309b1ca643767fe600a245a00517ece66327) on R-devel). This seems to be the root cause of errors.

`on_exit()` implementation in _development version_ is different and is using `eval()` (changed in [this commit](https://github.com/r-lib/ellipsis/commit/6f84df49c46cdca809deb8d0d10cacc6c0b5e3a6)), which might have already fixed the issue, but is not yet on CRAN.

cc @hadley, @lionel- , as this seems to be important ('ellipsis' is used in 'tidyr', which has many reverse dependencies).

**Comment by lionel-** [comment]
Context: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16538

Thanks we'll prepare a release soonish.

**Comment by palderman** [comment]
Prioritizing an updated release for `ellipse` would be very helpful. I'm trying to submit my updated package for compliance with upcoming release of `dplyr` 1.0.0 (per notice from @hadley last week), but my updated code is failing checks with R-devel on r-hub.

**Comment by hadley** [comment]
Fixed in https://github.com/r-lib/ellipsis/commit/6f84df49c46cdca809deb8d0d10cacc6c0b5e3a6 and now on CRAN.
